[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[build.nixpacks]
buildCommand = "cd backend && npm install"